const {chromium}=require('@playwright/test');const fs=require('node:fs'),path=require('node:path');
(async()=>{const base='http://127.0.0.1:3210';const catalog=JSON.parse(fs.readFileSync('public/assets/catalog.json','utf8'));const missing=[];for(const h of catalog.heroes)for(const field of ['img','icon','gif'])if(h[field]&&!fs.existsSync(path.join('public',decodeURIComponent(h[field]))))missing.push(h.name+':'+field);if(missing.length)throw Error('Missing assets: '+missing.join(', '));
const browser=await chromium.launch();const page=await browser.newPage({viewport:{width:1600,height:1100}}),errors=[];page.on('pageerror',e=>errors.push(e.message));const backup=await(await page.request.get(base+'/api/state')).json();
try{await page.goto(base);await page.waitForFunction(()=>typeof state!=='undefined'&&state);await page.click('[data-tab="teams"]');await page.click('[aria-label="blue hero 1 picker"]');await page.fill('.hero-search','Hirara');await page.locator('.hero-tile').filter({hasText:'Hirara'}).click();await page.waitForFunction(()=>state.blue.players[0].hero==='Hirara');await page.click('[aria-label="red ban 1 picker"]');await page.fill('.hero-search','Chou');await page.locator('.hero-tile').filter({hasText:'Chou'}).click();await page.waitForFunction(()=>state.red.bans[0]==='Chou');
const draft=structuredClone(backup);const picks=['Miya','Nana','Chou','Hirara','Aamon'];for(const [side,offset]of [['blue',0],['red',2]]){draft[side].players.forEach((p,i)=>p.hero=picks[(i+offset)%5]);draft[side].logo=catalog.logos[side==='blue'?0:1].url;}draft.visible=true;draft.scene='draft';await page.request.post(base+'/api/state',{data:draft});await page.screenshot({path:'data/teams-with-icons.png',fullPage:true});
const overlay=await browser.newPage({viewport:{width:1920,height:1080}});overlay.on('pageerror',e=>errors.push(e.message));await overlay.goto(base+'/overlay.html?scene=draft');await overlay.waitForSelector('.hero-gif-badge');await overlay.waitForFunction(()=>[...document.images].every(i=>i.complete&&i.naturalWidth>0));const animated=await overlay.locator('.heroimage').first().evaluate(e=>getComputedStyle(e).animationName);if(animated!=='portrait-drift')throw Error('Portrait animation not active');await overlay.screenshot({path:'data/draft-animated.png'});
await overlay.goto(base+'/overlay.html?scene=countdown');await overlay.waitForSelector('.vs-team img');await overlay.waitForFunction(()=>[...document.images].every(i=>i.complete&&i.naturalWidth>0));if(await overlay.locator('.vs-team img').count()!==2)throw Error('Missing team logo');const before=await overlay.locator('.aurora').first().evaluate(e=>getComputedStyle(e).transform);await overlay.waitForTimeout(600);const after=await overlay.locator('.aurora').first().evaluate(e=>getComputedStyle(e).transform);if(before===after)throw Error('Background did not animate');await overlay.screenshot({path:'data/starting-soon-animated.png'});
// OCR/stat updates must not restart the countdown scene's animated background.
await overlay.locator('.aurora').first().evaluate(e=>e.dataset.retained='yes');await page.request.post(base+'/api/state',{data:{blue:{kills:11}}});await overlay.waitForTimeout(150);if(await overlay.locator('.aurora').first().getAttribute('data-retained')!=='yes')throw Error('Unrelated stat update reset animation');
await page.click('[aria-label="blue hero 1 picker"]');await page.fill('.hero-search','');await page.screenshot({path:'data/hero-picker.png'});if(errors.length)throw Error(errors.join('\n'));console.log(JSON.stringify({heroes:catalog.heroes.length,downloadedIcons:catalog.iconArtworkCount,gifs:catalog.heroes.filter(h=>h.gif).length,missing,checks:['pick','ban','image decoding','portrait animation','VS logos','background motion','no stat-driven animation restart'],errors}));
}finally{await page.request.post(base+'/api/state',{data:backup});await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
