const {test}=require('node:test'),assert=require('node:assert/strict');const {defaults,merge,validate,timerAction}=require('../lib/state');const {normalize,numeric,findFeed}=require('../lib/parser');
test('reference JSON maps teams, players and compact gold',()=>{const p=normalize({data:{teamdata:{blueteam:{teamname:'USM',totalgold:'28.8k',score:'2',playerlist:Array.from({length:5},()=>({name:'Ace',hero:'Aamon',KDA:'2/1/3'}))}},game_duration:'10:08'}}).patch;assert.equal(p.blue.gold,28800);assert.equal(p.blue.name,'USM');assert.equal(p.gameTime,'10:08');assert.equal(p.blue.players.length,5);validate(merge(defaults(),p));});
test('mapping reads arrays and skips missing fields',()=>{const r=normalize({data:{camps:[{kills:12}]}},{'blue.kills':'data.camps[0].kills','red.kills':'data.camps.1.kills'});assert.equal(r.patch.blue.kills,12);assert.equal(r.warnings.length,1);});
test('provider errors and unknown responses do not silently succeed',()=>{assert.throws(()=>normalize({code:100006,message:'match not found',data:null}),/match not found/);assert.throws(()=>normalize({hello:3}),/Unrecognized/);assert.equal(findFeed({data:{matchUrl:'https://sg-api.mobilelegends.com/feed'}}),'https://sg-api.mobilelegends.com/feed');assert.throws(()=>numeric('n/a'));});
test('official battle schema is post-match only',()=>{assert.throws(()=>normalize({code:0,data:{status:'battle',isClosed:false,isValidate:true,battleData:{win_camp:0,red_camp_kill:7,player_list:null,blue_camp_kill:12,game_time:608}}}),/Post-match result is not available.*OCR Capture/);});
test('official battle schema maps completed result players, hero icons and items',()=>{const player=(camp,pos)=>({camp,pos,name:`P${camp}${pos}`,heroid:70,equip_list:[2306,3212,0],kill_num:pos,dead_num:1,assist_num:2,gold_total:7000+pos,max_level:12});const list=[0,1,2,3,4].flatMap(pos=>[player(1,pos),player(2,pos)]),assets={heroes:{70:{icon:'https://cdn.test/hero.jpg'}},items:{2306:{name:'Blade',icon:'https://cdn.test/blade.png'},3212:{name:'Boots',icon:'https://cdn.test/boots.png'}}};const p=normalize({status:'result',isClosed:false,battleData:{win_camp:1,red_camp_kill:18,blue_camp_kill:8,game_time:767,player_list:list}}, {},assets).patch;assert.equal(p.winner,'red');assert.equal(p.scene,'postgame');assert.equal(p.red.players.length,5);assert.equal(p.red.players[4].kda,'4/1/2');assert.equal(p.blue.players[0].gold,7000);assert.equal(p.blue.players[0].heroId,70);assert.equal(p.blue.players[0].heroIcon,'https://cdn.test/hero.jpg');assert.deepEqual(p.blue.players[0].items,[{id:2306,name:'Blade',icon:'https://cdn.test/blade.png'},{id:3212,name:'Boots',icon:'https://cdn.test/boots.png'}]);assert.equal(p.gameTime,'12:47');validate(merge(defaults(),p));});
test('timer pause/resume and expiry preserve elapsed time',()=>{let t={duration:30,remaining:30,endAt:null};t=timerAction(t,'start',null,1000);t=timerAction(t,'pause',null,11000);assert.equal(t.remaining,20);t=timerAction(t,'start',null,12000);assert.equal(t.endAt,32000);t=timerAction(t,'pause',null,40000);assert.equal(t.remaining,0);assert.throws(()=>timerAction(t,'reset',-1));});
test('reject malformed state and prototype pollution',()=>{assert.throws(()=>merge(defaults(),JSON.parse('{"__proto__":{"polluted":true}}')));assert.throws(()=>validate(merge(defaults(),{blue:{kills:-1}})));assert.throws(()=>validate(merge(defaults(),{red:{players:[]}})));assert.equal({}.polluted,undefined);});
test('battle objectives aggregate player tower/lord/turtle and fallback to live state',()=>{const player=(camp,pos,towers=0,lord=0,turtle=0)=>({camp,pos,name:`P${camp}${pos}`,heroid:70,equip_list:[],kill_num:1,dead_num:1,assist_num:1,gold_total:5000,max_level:10,destroy_tower_num:towers,kill_lord_num:lord,kill_turtle_num:turtle});const list=[...[0,1,2,3,4].map(pos=>player(1,pos,pos===0?3:pos===1?2:0,pos===0?1:0,pos===1?2:0)),...[0,1,2,3,4].map(pos=>player(2,pos,0,0,0))];const parsed=normalize({status:'result',isClosed:false,battleData:{win_camp:1,red_camp_kill:10,blue_camp_kill:5,game_time:600,player_list:list}},{},{},{blue:{turrets:2,lord:0,turtle:1}}).patch;assert.equal(parsed.red.turrets,5);assert.equal(parsed.red.lord,1);assert.equal(parsed.red.turtle,2);assert.equal(parsed.blue.turrets,2);assert.equal(parsed.blue.turtle,1);});
test('validate accepts valid telemetry kills and rejects malformed telemetry',()=>{const s=defaults();s.telemetry={kills:[{time:'01:44',side:'blue',killer:'KZO',victim:'Sensui',x:44.3,y:266.2}]};assert.doesNotThrow(()=>validate(s));assert.throws(()=>validate({...s,telemetry:{kills:[{time:'01:44',side:'green'}]}}),/Invalid telemetry kill entry/);assert.throws(()=>validate({...s,telemetry:'not an object'}),/Invalid telemetry/);});

