const {chromium}=require('@playwright/test');const fs=require('fs');
(async()=>{const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1600,height:1050}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:3210');await page.waitForFunction(()=>document.querySelector('#connection').textContent.includes('connected'));await page.screenshot({path:'data/control-panel.png',fullPage:true});
const backup=await (await page.request.get('http://127.0.0.1:3210/api/state')).json();await page.click('[data-tab="data"]');await page.fill('#raw',JSON.stringify({teamdata:{blueteam:{teamname:'TEST BLUE',totalgold:'28.8k'},redteam:{teamname:'TEST RED',kills:7}}}));await page.click('#parseJson');await page.waitForFunction(()=>!document.querySelector('#applyParsed').disabled);await page.click('#applyParsed');await page.waitForFunction(()=>state.blue.name==='TEST BLUE');
const original=await (await page.request.get('http://127.0.0.1:3210/api/state')).json();await page.request.post('http://127.0.0.1:3210/api/timer',{data:{timer:'countdown',action:'reset',seconds:5}});await page.request.post('http://127.0.0.1:3210/api/timer',{data:{timer:'countdown',action:'start'}});const overlay=await browser.newPage({viewport:{width:1920,height:1080}});overlay.on('pageerror',e=>errors.push(e.message));await overlay.goto('http://127.0.0.1:3210/overlay.html?scene=countdown');await overlay.waitForSelector('.bigclock');await overlay.waitForTimeout(1100);const clock=await overlay.locator('.bigclock').textContent();if(clock==='00:05')throw Error('Timer did not tick');
for(const scene of ['draft','scoreboard','countdown','postgame','schedule']){await overlay.goto('http://127.0.0.1:3210/overlay.html?scene='+scene);await overlay.waitForTimeout(300);await overlay.screenshot({path:'data/hud-'+scene+'.png'});}
const ocr=await page.evaluate(async()=>{const w=await Tesseract.createWorker('eng',1,{workerPath:'/vendor/tesseract/worker.min.js',corePath:location.origin+'/vendor/core',langPath:location.origin+'/vendor/lang'});await w.setParameters({tessedit_pageseg_mode:'7'});const c=document.createElement('canvas');c.width=500;c.height=100;const x=c.getContext('2d');x.fillStyle='white';x.fillRect(0,0,500,100);x.fillStyle='black';x.font='60px Arial';x.fillText('28.8k',20,75);const r=await w.recognize(c);await w.terminate();return r.data.text.trim();});if(!ocr.includes('28.8'))throw Error('OCR failed: '+ocr);
await page.request.post('http://127.0.0.1:3210/api/state',{data:backup});await browser.close();if(errors.length)throw Error(errors.join('\n'));console.log(JSON.stringify({browser:'Chromium',scenes:5,parser:'passed',timer:clock,ocr,errors}));})().catch(e=>{console.error(e);process.exit(1);});



