const {chromium}=require('@playwright/test');const {spawn}=require('node:child_process');const fs=require('node:fs'),os=require('node:os'),path=require('node:path');
(async()=>{const base='http://127.0.0.1:3219',child=spawn(process.execPath,['server.js'],{env:{...process.env,PORT:'3219',DATA_DIR:fs.mkdtempSync(path.join(os.tmpdir(),'ml-real-ocr-'))},windowsHide:true});let browser;try{
for(let i=0;i<60;i++){try{if((await fetch(base+'/api/state')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
browser=await chromium.launch();const overlay=await browser.newPage({viewport:{width:1920,height:1080},reducedMotion:'reduce'});await overlay.request.post(base+'/api/state',{data:{scene:'scoreboard',blue:{kills:4},red:{kills:2},gameTime:'01:47'}});await overlay.goto(base+'/overlay.html');await overlay.waitForSelector('.reference-scoreboard');await overlay.waitForTimeout(150);const ui=await browser.newPage({viewport:{width:1600,height:1100}}),errors=[];ui.on('pageerror',e=>errors.push(e.message));await ui.goto(base);await ui.waitForFunction(()=>state?.scene);await ui.click('nav [data-tab=ocr]');await ui.selectOption('#ocrProfile','scoreboard');
let sample=process.argv[2];let regions;if(sample){regions=[{field:'blue.kills',x:439*1920/1024,y:40*1080/576,w:49*1920/1024,h:40*1080/576},{field:'red.kills',x:605*1920/1024,y:44*1080/576,w:35*1920/1024,h:35*1080/576},{field:'gameTime',x:519*1920/1024,y:31*1080/576,w:49*1920/1024,h:17*1080/576}];}else{
fs.mkdirSync('data',{recursive:true});sample='data/ocr-scoreboard-fixture.png';await overlay.screenshot({path:sample});regions=await overlay.evaluate(()=>[['blue.kills','.sb-kills.blue'],['red.kills','.sb-kills.red'],['gameTime','.sb-center>strong']].map(([field,selector])=>{const el=document.querySelector(selector),range=document.createRange();range.selectNodeContents(el);const r=range.getBoundingClientRect();return {field,x:Math.floor(r.x-3),y:Math.max(0,Math.floor(r.y)),w:Math.ceil(r.width+6),h:Math.ceil(r.height)};}));}
await ui.setInputFiles('#ocrImage',sample);await ui.waitForFunction(()=>!!stillImage);await ui.fill('#regions',JSON.stringify(regions));await ui.click('#saveRegions');await ui.click('#scan');await ui.waitForFunction(()=>!ocrBusy&&results.size===3,{},{timeout:60000});const readings=await ui.evaluate(()=>[...results.values()]);console.log('REAL OCR',JSON.stringify(readings));if(!sample.includes('feedback')){for(const [field,value] of [['blue.kills',4],['red.kills',2],['gameTime','01:47']]){if(!readings.some(r=>r.field===field&&r.value===value&&r.accepted))throw Error('OCR missed '+field);}
await overlay.request.post(base+'/api/state',{data:{blue:{kills:0},red:{kills:0}}});await ui.check('#ocrAutoApply');const start=performance.now();await ui.click('#autoOcr');await overlay.waitForFunction(()=>state.blue.kills===4&&state.red.kills===2,{},{timeout:15000});const loopMs=Math.round(performance.now()-start);await ui.click('#autoOcr');console.log('PASS real Tesseract and two-frame continuous confirmation: '+loopMs+' ms to update both kill fields');}
if(errors.length)throw Error(errors.join('\n'));await ui.screenshot({path:'data/ocr-real-test.png'});
}finally{await browser?.close();child.kill();}})().catch(e=>{console.error(e);process.exitCode=1});
