const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {chromium}=require('@playwright/test');
process.env.DATA_DIR=fs.mkdtempSync(path.join(os.tmpdir(),'swiss-motion-'));
const {app}=require('../server');
const teams=require('../public/assets/swiss-bracket-logos.json').map(t=>t.name);
(async()=>{
  const server=app.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));
  const base='http://127.0.0.1:'+server.address().port,browser=await chromium.launch();
  try {
    const context=await browser.newContext({viewport:{width:1920,height:1080},reducedMotion:'no-preference'});
    const output=await context.newPage(),panel=await context.newPage(),errors=[];
    output.on('pageerror',error=>errors.push(error.message));panel.on('pageerror',error=>errors.push(error.message));
    const post=async(url,data)=>{const r=await output.request.post(base+url,{data});assert.ok(r.ok(),await r.text());return r.json();};
    await post('/api/swiss/start',{teams});
    await output.goto(base+'/overlay.html?scene=swiss');await output.waitForSelector('.swiss-bracket[data-ready=true]');
    assert.equal(await output.locator('[data-swiss-flight]').count(),0);
    const font=await output.locator('[data-slot="R1M1/blue"] text').getAttribute('font-size');assert.equal(font,'19');
    assert.equal(await output.locator('#swiss-logo-7 image').getAttribute('data-source'),'/assets/logos/DEVCOM.png');
    await output.screenshot({path:'data/swiss-large-overview.png'});
    await panel.goto(base+'/#tournament');await panel.waitForSelector('#swissView');
    await panel.selectOption('#swissView','r1-upper');
    await output.waitForSelector('.swiss-bracket[data-view="r1-upper"]');
    await output.waitForFunction(()=>!document.querySelector('.swiss-bracket').dataset.camera);
    const enlarged=await output.locator('[data-slot="R1M1/blue"] text').boundingBox();assert.ok(enlarged.height>40,'Close-up text should exceed 40px');
    await output.screenshot({path:'data/swiss-large-closeup.png'});
    await output.reload();await output.waitForSelector('.swiss-bracket[data-view="r1-upper"][data-ready=true]');
    await panel.selectOption('#swissView','overview');
    await output.waitForFunction(()=>document.querySelector('.swiss-bracket').dataset.view==='overview'&&!document.querySelector('.swiss-bracket').dataset.camera);
    for(let i=1;i<=7;i++)await post('/api/swiss/result',{matchId:'R1M'+i,winner:'blue'});
    await output.waitForSelector('[data-slot="R1M7/blue"][data-result=win]');
    await post('/api/swiss/result',{matchId:'R1M8',winner:'blue'});
    await output.waitForFunction(()=>document.querySelectorAll('[data-swiss-flight]').length===16);
    await output.evaluate(()=>render());
    assert.equal(await output.locator('[data-swiss-flight]').count(),16,'Unrelated renders must preserve running advancement animations');
    await output.screenshot({path:'data/swiss-advancing.png'});
    const snapshot=await output.evaluate(()=>SwissBracket.serialize(document.querySelector('.swiss-bracket')));
    assert.ok(snapshot.includes('width="3840"'));assert.ok(!snapshot.includes('data-swiss-flight'));
    assert.ok(!/<g[^>]*data-slot[^>]*style="[^"]*opacity: 0/.test(snapshot));
    await output.waitForFunction(()=>!document.querySelector('[data-swiss-motion]'));
    assert.equal(await output.locator('[data-match-id]').count(),16);
    const allVisible=await output.locator('[data-slot]').evaluateAll(slots=>slots.every(slot=>getComputedStyle(slot).opacity!=='0'));assert.ok(allVisible);
    let state=await (await output.request.get(base+'/api/state')).json();
    for(const match of state.swiss.rounds.at(-1).matches)await post('/api/swiss/result',{matchId:match.id,winner:'blue'});
    await output.waitForSelector('[data-match-id=R3M1]');
    await output.waitForFunction(()=>!document.querySelector('[data-swiss-motion]'));
    await post('/api/swiss/result',{matchId:'R3M1',winner:'blue'});
    await output.waitForFunction(()=>document.querySelector('[data-finish="3-0"] [data-team]')&&document.querySelector('[data-swiss-flight]'));
    // A rapid second result must finish the previous movement without leaving hidden slots.
    await post('/api/swiss/result',{matchId:'R3M2',winner:'red'});
    await output.waitForFunction(()=>document.querySelectorAll('[data-finish="3-0"] [data-team]').length===2&&!document.querySelector('[data-swiss-motion]'));
    assert.ok(await output.locator('[data-slot]').evaluateAll(slots=>slots.every(slot=>getComputedStyle(slot).opacity!=='0')));
    await output.emulateMedia({reducedMotion:'reduce'});
    await post('/api/swiss/result',{matchId:'R3M7',winner:'blue'});
    await output.waitForSelector('[data-slot="R3M7/blue"][data-result=win]');
    assert.equal(await output.locator('[data-swiss-flight]').count(),0);
    await output.setViewportSize({width:3840,height:2160});
    const dimensions=await output.locator('.swiss-bracket>svg').boundingBox();assert.equal(dimensions.width,3840);assert.equal(dimensions.height,2160);
    assert.equal(await output.locator('#stage').evaluate(el=>el.style.transform),'none');
    await output.screenshot({path:'data/swiss-native-4k.png'});
    assert.deepEqual(errors,[]);
    console.log('PASS larger labels, close-ups and persistence, original DEVCOM file, advancing-team motion, interruption cleanup, reduced motion, 4K rendering/export.');
  } finally {await browser.close();server.closeAllConnections();await new Promise(resolve=>server.close(resolve));}
})().catch(error=>{console.error(error);process.exitCode=1;});
