const forbidden=['__proto__','constructor','prototype'];
function get(obj,path){return String(path).replace(/\[(\d+)\]/g,'.$1').split('.').filter(Boolean).reduce((v,k)=>forbidden.includes(k)?undefined:v?.[k],obj);}
function set(obj,path,value){const keys=path.split('.');if(keys.some(k=>forbidden.includes(k)))throw Error('Invalid mapping path');let p=obj;keys.forEach((k,i)=>{if(i===keys.length-1)p[k]=value;else p=p[k]??=(/^\d+$/.test(keys[i+1])?[]:{});});}
function numeric(v){if(typeof v==='number')return v;const m=String(v).replace(/,/g,'').trim().match(/^(\d+(?:\.\d+)?)\s*([km])?$/i);if(!m)throw Error(`Invalid number: ${v}`);return Number(m[1])*({k:1000,m:1000000}[m[2]?.toLowerCase()]||1);}
function normalize(raw,mapping={}){if(!raw||typeof raw!=='object')throw Error('Expected a JSON object');if(raw.code!==undefined&&![0,200,'0','200'].includes(raw.code))throw Error(raw.message||`API error ${raw.code}`);let d=raw.data??raw;if(typeof d==='string'){try{d=JSON.parse(d);}catch{throw Error('Response contains a URL or text; resolve the match feed first');}}const patch={},warnings=[];
 const root=d.matchdata??d;const teams=root.teamdata??root.teams??root;
 for(const [side,aliases] of Object.entries({blue:['blue','blueteam','blueTeam'],red:['red','redteam','redTeam']})){const t=aliases.map(k=>teams[k]).find(v=>v&&typeof v==='object');if(!t)continue;const out={};for(const [dest,srcs] of Object.entries({name:['name','teamname','teamName'],tag:['tag'],score:['score'],kills:['kills','killscore'],gold:['gold','totalgold'],turrets:['turrets','turret'],lord:['lord'],turtle:['turtle']})){const v=srcs.map(k=>t[k]).find(v=>v!==undefined);if(v!==undefined)out[dest]=['name','tag'].includes(dest)?String(v):numeric(v);}const players=t.players??t.playerlist;if(Array.isArray(players)&&players.length===5)out.players=players.map((p,i)=>({name:String(p.name??p.nickname??`Player ${i+1}`),role:String(p.role??['EXP','JUNGLE','MID','GOLD','ROAM'][i]),hero:String(p.hero??p.heroName??''),kda:String(p.kda??p.KDA??'0/0/0'),gold:numeric(p.gold??0)}));if(Array.isArray(t.bans)&&t.bans.length===3)out.bans=t.bans.map(v=>String(v?.name??v));patch[side]=out;}
 if(root.gameTime!==undefined||root.game_duration!==undefined)patch.gameTime=String(root.gameTime??root.game_duration);
 for(const [destination,source]of Object.entries(mapping)){if(!/^(gameTime|phase|blue\.(name|tag|score|kills|gold|turrets|lord|turtle)|red\.(name|tag|score|kills|gold|turrets|lord|turtle))$/.test(destination))throw Error(`Unsupported destination: ${destination}`);const v=get(raw,source);if(v===undefined){warnings.push(`Missing: ${source}`);continue;}set(patch,destination,/\.(score|kills|gold|turrets|lord|turtle)$/.test(destination)?numeric(v):String(v));}
 if(!Object.keys(patch).length)throw Error('Unrecognized schema. Inspect raw JSON and add field mappings. No broadcast data changed.');return {patch,warnings};}
function findFeed(raw){const candidates=[raw?.data,raw?.data?.url,raw?.data?.matchUrl,raw?.data?.match_url,raw?.url];return candidates.find(v=>typeof v==='string'&&/^https:\/\//.test(v));}
module.exports={normalize,get,numeric,findFeed};
