from pathlib import Path
p=Path('lib/state.js');s=p.read_text(encoding='utf-8-sig');s=s.replace("kda:'0/0/0',gold:0","kda:'0/0/0',gold:0,level:0");s=s.replace("for(const k of ['game','bestOf'])if(!Number.isInteger(s[k])||s[k]<1||s[k]>99)throw Error(`Invalid ${k}`);","if(![3,5,7].includes(s.bestOf))throw Error('Choose Best of 3, Best of 5, or Best of 7');if(!Number.isInteger(s.game)||s.game<1||s.game>s.bestOf)throw Error('Game number must be within the selected series');");s=s.replace("if(!Number.isFinite(p.gold)||p.gold<0)throw Error('Invalid player gold');","if(!Number.isFinite(p.gold)||p.gold<0)throw Error('Invalid player gold');if(p.level!==undefined&&(!Number.isInteger(p.level)||p.level<0||p.level>15))throw Error('Player level must be 0–15');");s=s.replace("'sponsors','ads'].includes", "'sponsors','ads','players'].includes");p.write_text(s,encoding='utf-8')
p=Path('public/index.html');s=p.read_text(encoding='utf-8-sig');s=s.replace('<input type="number" min="1" data-path="bestOf">','<select data-path="bestOf"><option value="3">Best of 3</option><option value="5">Best of 5</option><option value="7">Best of 7 · Championship</option></select>');s=s.replace('01—08','01—09');s=s.replace('<script src="/ocr.js">','<script src="/ocr-model.js"></script><script src="/ocr.js">');p.write_text(s,encoding='utf-8')
p=Path('public/app.js');s=p.read_text(encoding='utf-8-sig');s=s.replace("['ads','Ad break','Images, video & playlist rotation']","['ads','Ad break','Images, video & playlist rotation'],['players','Player stat rails','Names, heroes, levels, KDA & gold']");s=s.replace("el.type==='number'?Number(el.value):el.value","el.type==='number'||el.dataset.path==='bestOf'?Number(el.value):el.value");s=s.replace("save(patchAt(el.dataset.path,", "save(patchAt(el.dataset.path,")
# Clamp the current game when switching to a shorter fixed series.
s=s.replace("el.onchange=run(()=>save(patchAt(el.dataset.path,el.type==='number'||el.dataset.path==='bestOf'?Number(el.value):el.value)))", "el.onchange=run(()=>el.dataset.path==='bestOf'?save({bestOf:Number(el.value),game:Math.min(state.game,Number(el.value))}):save(patchAt(el.dataset.path,el.type==='number'?Number(el.value):el.value)))")
s=s.replace('<input aria-label="${side} KDA ${i+1}" data-player="${side}.${i}.kda" placeholder="K/D/A">','<input aria-label="${side} KDA ${i+1}" data-player="${side}.${i}.kda" placeholder="K/D/A"><input aria-label="${side} gold ${i+1}" type="number" min="0" data-player="${side}.${i}.gold" placeholder="Gold"><input aria-label="${side} level ${i+1}" type="number" min="0" max="15" data-player="${side}.${i}.level" placeholder="Level">');s=s.replace('players[i][k]=el.value','players[i][k]=[\'gold\',\'level\'].includes(k)?Number(el.value):el.value');p.write_text(s,encoding='utf-8')
p=Path('public/overlay.html');s=p.read_text(encoding='utf-8-sig');s=s.replace('</head>','<link rel="stylesheet" href="/broadcast-unified.css"></head>');s=s.replace('<script src="/overlay.js">','<script src="/broadcast-unified.js"></script><script src="/overlay.js">');p.write_text(s,encoding='utf-8')
p=Path('public/overlay.js');s=p.read_text(encoding='utf-8-sig');s=s.replace("const s=state;", "const s=state;if(renderUnified(scene,s))return;",1);s=s.replace("if(['intermission','sponsors','ads'].includes(scene))return JSON.stringify([...common,s.ticker,s.breakTimer,s.breaks]);if(scene==='countdown')return JSON.stringify([...common,s.countdown,s.ticker,...['blue','red'].map(k=>[s[k].name,s[k].tag,s[k].logo])]);", "if(['intermission','sponsors','ads','countdown'].includes(scene))return JSON.stringify([...common,s.countdown,s.breakTimer,s.ticker,s.breaks,s.schedule,s.bestOf,...['blue','red'].map(k=>[s[k].name,s[k].tag,s[k].logo])]);")
s=s.replace("[...common,s.game,s.phase,s.draftTimer", "[...common,s.bestOf,s.game,s.phase,s.breaks.sponsors,s.draftTimer")
p.write_text(s,encoding='utf-8')
p=Path('public/style.css');s=p.read_text(encoding='utf-8-sig');s+='\n.playerrow{grid-template-columns:45px minmax(80px,1fr) minmax(100px,1fr) 75px 75px 50px}.playerrow input{min-width:0}@media(max-width:1300px){#teamEditors{grid-template-columns:1fr}}\n';p.write_text(s,encoding='utf-8')
