from pathlib import Path
p=Path('public/index.html');s=p.read_text(encoding='utf-8-sig').replace('/ocr.js','/ocr-v2.js');s=s.replace('</head>','<link rel="stylesheet" href="/edit-transitions.css"></head>');s=s.replace('</body>','<script src="/click-edit.js"></script><script src="/hero-motion-control.js"></script></body>');p.write_text(s,encoding='utf-8')
p=Path('public/overlay.html');s=p.read_text(encoding='utf-8-sig').replace('</head>','<link rel="stylesheet" href="/edit-transitions.css"></head>');s=s.replace('</body>','<script src="/transitions.js"></script><script src="/preview-edit.js"></script></body>');p.write_text(s,encoding='utf-8')
p=Path('public/hero-picker.js');s=p.read_text(encoding='utf-8-sig').replace("h.gif?'<small>GIF</small>'", "h.animation?'<small>MOTION</small>'");s=s.replace("'<div class=\"picker-heading\">", "'<div class=\"picker-heading\">")
s=s.replace('<div class="hero-grid"></div>', '<label class="check"><input type="checkbox" class="motion-only"> Only heroes with moving draft artwork</label><div class="hero-grid"></div>');s=s.replace("library.filter(h=>key(h.name).includes(key(search.value)))", "library.filter(h=>key(h.name).includes(key(search.value))&&(!dialog.querySelector('.motion-only').checked||h.animation))");s=s.replace('search.oninput=paint;',"search.oninput=paint;dialog.querySelector('.motion-only').onchange=paint;");s=s.replace('sync();\n})();', "events.addEventListener('catalog',()=>fetch('/assets/catalog.json',{cache:'no-store'}).then(r=>r.json()).then(c=>{library=c.heroes;sync();paint();}));sync();\n})();");p.write_text(s,encoding='utf-8')
p=Path('public/broadcast-unified.js');s=p.read_text(encoding='utf-8-sig').replace('class="draft-hero-media" src="${esc(h.animation)}"', 'class="draft-hero-media" style="object-position:${h.animationPosition??50}% 50%" src="${esc(h.animation)}"');p.write_text(s,encoding='utf-8')
p=Path('public/overlay.js');s=p.read_text(encoding='utf-8-sig');s+="\nevents.addEventListener('catalog',()=>fetch('/assets/catalog.json',{cache:'no-store'}).then(r=>r.json()).then(c=>{catalog=c;render();}));\n";p.write_text(s,encoding='utf-8')
p=Path('public/transitions.js');s=p.read_text(encoding='utf-8-sig');s=s.replace("const original=render;", "const original=render;const signature=e=>e.textContent+[...e.querySelectorAll('img,video')].map(m=>m.getAttribute('src')).join('|');");s=s.replace('oldValues.set(selector+i,e.innerHTML)','oldValues.set(selector+i,signature(e))').replace('oldValues.get(selector+i)!==e.innerHTML','oldValues.get(selector+i)!==signature(e)');p.write_text(s,encoding='utf-8')
p=Path('server.js');s=p.read_text(encoding='utf-8-sig');old="state=validate(merge(state,JSON.parse(fs.readFileSync(file,'utf8'))));";new="const saved=JSON.parse(fs.readFileSync(file,'utf8'));if(![3,5,7].includes(saved.bestOf)){fs.copyFileSync(file,file+'.before-series-fix');saved.bestOf=3;saved.game=Math.min(Math.max(1,saved.game||1),3);}state=validate(merge(state,saved));";assert old in s;s=s.replace(old,new);route="""app.post('/api/hero/animation',(req,res)=>{const catalogPath=path.join(__dirname,'public/assets/catalog.json');const catalog=JSON.parse(fs.readFileSync(catalogPath,'utf8'));const h=catalog.heroes.find(h=>h.name===req.body.hero);if(!h)throw Error('Unknown hero');const position=Number(req.body.position??50);if(!Number.isFinite(position)||position<0||position>100)throw Error('Position must be 0–100');if(req.body.src!==undefined){const src=req.body.src;if(typeof src!=='string'||!/^\\/assets\\/uploads\\/[a-f0-9]{64}\\.(gif|mp4|webm)$/.test(src)||!fs.existsSync(path.join(__dirname,'public',src)))throw Error('Upload a GIF, MP4 or WebM first');h.animation=src;h.animationSource='User-uploaded media';}h.animationPosition=position;fs.writeFileSync(catalogPath+'.tmp',JSON.stringify(catalog,null,2));fs.renameSync(catalogPath+'.tmp',catalogPath);for(const client of clients)client.write('event: catalog\\ndata: {}\\n\\n');res.json({hero:h});});\n""";s=s.replace("app.post('/api/match/parse'",route+"app.post('/api/match/parse'");p.write_text(s,encoding='utf-8')
